In [129]:
import pandas as pd

In [130]:
data = pd.read_csv(r"Datasets\train.csv")
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [131]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [132]:
for column_name, none_values in data.isnull().sum().items():
    print(f'{column_name}: {none_values}')

PassengerId: 0
Survived: 0
Pclass: 0
Name: 0
Sex: 0
Age: 177
SibSp: 0
Parch: 0
Ticket: 0
Fare: 0
Cabin: 687
Embarked: 2

In [133]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(data.drop(columns=['Survived'])
                                                 ,data['Survived'],test_size=0.1)

In [134]:
X_train

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
466,467,2,"Campbell, Mr. William",male,NaN,0,0,239853,0.0000,NaN,S
178,179,2,"Hale, Mr. Reginald",male,30.0,0,0,250653,13.0000,NaN,S
204,205,3,"Cohen, Mr. Gurshon ""Gus""",male,18.0,0,0,A/5 3540,8.0500,NaN,S
107,108,3,"Moss, Mr. Albert Johan",male,NaN,0,0,312991,7.7750,NaN,S
499,500,3,"Svensson, Mr. Olof",male,24.0,0,0,350035,7.7958,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
752,753,3,"Vande Velde, Mr. Johannes Joseph",male,33.0,0,0,345780,9.5000,NaN,S
226,227,2,"Mellors, Mr. William John",male,19.0,0,0,SW/PP 751,10.5000,NaN,S
27,28,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
581,582,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.0,1,1,17421,110.8833,C68,C
50,51,3,"Panula, Master. Juha Niilo",male,7.0,4,1,3101295,39.6875,NaN,S

In [135]:
X_test

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
493,494,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
717,718,2,"Troutt, Miss. Edwina Celia ""Winnie""",female,27.0,0,0,34218,10.5000,E101,S
284,285,1,"Smith, Mr. Richard William",male,NaN,0,0,113056,26.0000,A19,S
588,589,3,"Gilinski, Mr. Eliezer",male,22.0,0,0,14973,8.0500,NaN,S
437,438,2,"Richards, Mrs. Sidney (Emily Hocking)",female,24.0,2,3,29106,18.7500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
652,653,3,"Kalvik, Mr. Johannes Halvorsen",male,21.0,0,0,8475,8.4333,NaN,S
845,846,3,"Abbing, Mr. Anthony",male,42.0,0,0,C.A. 5547,7.5500,NaN,S
378,379,3,"Betros, Mr. Tannous",male,20.0,0,0,2648,4.0125,NaN,C
456,457,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
743,744,3,"McNamee, Mr. Neal",male,24.0,1,0,376566,16.1000,NaN,S

In [136]:
from sklearn.impute import SimpleImputer

si = SimpleImputer()

X_train_value = si.fit_transform(X_train[['Age']])

X_test_value = si.fit_transform(X_test[['Age']])

X_train_value.shape

(801, 1)

In [137]:
from sklearn.preprocessing import OrdinalEncoder

ode = OrdinalEncoder(categories=[['female','male']])

X_train_sex = ode.fit_transform(X_train[['Sex']])
X_test_sex = ode.transform(X_test[['Sex']])

X_train_sex.shape

(801, 1)

In [138]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first', sparse_output=False)

X_train_Embarked = ohe.fit_transform(X_train[['Embarked']])

X_test_Embarked = ohe.transform(X_test[['Embarked']])

X_train_Embarked.shape

(801, 3)

In [139]:
import numpy as np

In [140]:
X_train_transformed = np.concatenate((X_train_sex,X_train_Embarked,X_train_value),axis=1)

X_test_transformed = np.concatenate((X_test_sex,X_test_Embarked,X_test_value),axis=1)

X_train_transformed.shape

(801, 5)

In [141]:
from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['Age']),
    ('tnf2',OrdinalEncoder(categories=[['female','male']]),['Sex']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['Embarked'])
],remainder='drop')

In [142]:
data1 = transformer.fit_transform(X_train)

In [143]:
data1.shape

(801, 5)

In [144]:
print(data1)

[[29.67433697  1.          0.          1.          0.        ]
 [30.          1.          0.          1.          0.        ]
 [18.          1.          0.          1.          0.        ]
 ...
 [19.          1.          0.          1.          0.        ]
 [39.          0.          0.          0.          0.        ]
 [ 7.          1.          0.          1.          0.        ]]