In [225]:
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [226]:
data = pd.read_csv(r"Datasets\train.csv")
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [227]:
newdata = data[['Age','Embarked','Survived']]
print(newdata.head())

    Age Embarked  Survived
0  22.0        S         0
1  38.0        C         1
2  26.0        S         1
3  35.0        S         1
4  35.0        S         0

In [228]:
mapping = {'S': 0, 'C': 1, 'Q': 2}
newdata['Embarked'] = newdata['Embarked'].map(mapping).fillna(0).astype(int)

In [229]:
newdata['Embarked'].value_counts()

Embarked
0    646
1    168
2     77
Name: count, dtype: int64

In [230]:
newdata.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Age       714 non-null    float64
 1   Embarked  891 non-null    int64
 2   Survived  891 non-null    int64
dtypes: float64(1), int64(2)
memory usage: 21.0 KB

In [231]:
newdata.isnull().mean()

Age         0.198653
Embarked    0.000000
Survived    0.000000
dtype: float64

In [232]:
x = newdata.drop(columns=['Survived'])
y = newdata['Survived']
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
X_train.head()

      Age  Embarked
331  45.5         0
733  23.0         0
382  32.0         0
704  26.0         0
813   6.0         0

In [233]:
X_train.shape, X_test.shape

((712, 2), (179, 2))

In [234]:
X_train.isnull().mean()

Age         0.196629
Embarked    0.000000
dtype: float64

In [240]:
mean_age = X_train['Age'].mean()
median_age = X_train['Age'].median()

mean_Embarked = X_train['Embarked'].mean()
median_Embarked = X_train['Embarked'].median()

np.float64(0.3441011235955056)

In [241]:
X_train['Age_median'] = X_train['Age'].fillna(median_age)
X_train['Age_mean'] = X_train['Age'].fillna(mean_age)

X_train['Embarked_median'] = X_train['Embarked'].fillna(median_Embarked)
X_train['Embarked_mean'] = X_train['Embarked'].fillna(mean_Embarked)

In [242]:
X_train.sample(10)

      Age  Embarked  Age_median   Age_mean
301   NaN         2        28.0  29.498846
760   NaN         0        28.0  29.498846
867  31.0         0        31.0  31.000000
821  27.0         0        27.0  27.000000
334   NaN         0        28.0  29.498846
133  29.0         0        29.0  29.000000
489   9.0         0         9.0   9.000000
735  28.5         0        28.5  28.500000
88   23.0         0        23.0  23.000000
484  25.0         1        25.0  25.000000

In [243]:
print('Original Age variable variance: ', X_train['Age'].var())
print('Age Variance after median imputation: ', X_train['Age_median'].var())
print('Age Variance after mean imputation: ', X_train['Age_mean'].var())

print('Original Embarked variable variance: ', X_train['Embarked'].var())
print('Embarked Variance after median imputation: ', X_train['Embarked_median'].var())
print('Embarked Variance after mean imputation: ', X_train['Embarked_mean'].var())

Original Age variable variance:  210.2517072477435
Age Variance after median imputation:  169.20731007048155
Age Variance after mean imputation:  168.85193366872227
Original Emabaked variable variance:  0.39478934559648543

KeyError: 'median_Emabarked'