<a href="https://colab.research.google.com/github/sunildhakad2004/Machine_Learning_100Days/blob/main/house-price-prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd

In [20]:
data = {
    "Area": [800, 1000, 1200, 1500, 1800,
             2000, 2200, 2500, 2800, 3000,
             1600, 2400, 1100, 1900, 2700],
    "Bedrooms": [2, 2, 3, 3, 3, 4, 4, 4, 5, 5,
                 3, 4, 2, 3, 5],
    "Age": [15, 10, 8, 5, 12, 6, 10, 4, 7, 3,
            15, 8, 20, 9, 5],
    "Price": [35, 45, 58, 75, 82, 105, 110, 135,
              148, 165, 72, 125, 40, 90, 155]
}

In [21]:
data = pd.DataFrame(data)
print(data)

    Area  Bedrooms  Age  Price
0    800         2   15     35
1   1000         2   10     45
2   1200         3    8     58
3   1500         3    5     75
4   1800         3   12     82
5   2000         4    6    105
6   2200         4   10    110
7   2500         4    4    135
8   2800         5    7    148
9   3000         5    3    165
10  1600         3   15     72
11  2400         4    8    125
12  1100         2   20     40
13  1900         3    9     90
14  2700         5    5    155

In [22]:
data.describe()

              Area   Bedrooms        Age       Price
count    15.000000  15.000000  15.000000   15.000000
mean   1900.000000   3.466667   9.133333   96.000000
std     695.906398   1.060099   4.718757   42.875234
min     800.000000   2.000000   3.000000   35.000000
25%    1350.000000   3.000000   5.500000   65.000000
50%    1900.000000   3.000000   8.000000   90.000000
75%    2450.000000   4.000000  11.000000  130.000000
max    3000.000000   5.000000  20.000000  165.000000

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [24]:
x_train,x_test,y_train,y_test = train_test_split(data.drop('Price',axis=1),data['Price'],test_size=0.2,random_state=0)

In [25]:
x_train

    Area  Bedrooms  Age
9   3000         5    3
14  2700         5    5
4   1800         3   12
2   1200         3    8
13  1900         3    9
10  1600         3   15
7   2500         4    4
11  2400         4    8
3   1500         3    5
0    800         2   15
5   2000         4    6
12  1100         2   20

In [26]:
y_test

1     45
6    110
8    148
Name: Price, dtype: int64

In [27]:
model = LinearRegression()

In [28]:
model.fit(x_train,y_train)

LinearRegression()

In [31]:
predictions = model.predict(x_test)
print(predictions)

[ 39.61294607 115.33753508 154.59750902]

In [30]:
print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)
print("R2 Score:", r2_score(y_test, predictions))
print("MAE:", mean_absolute_error(y_test, predictions))

Coefficients: [ 0.04442236 11.2088763  -0.46589314]
Intercept: -22.568238773055555
R2 Score: 0.9813791455760296
MAE: 5.7740326784282985

In [34]:
new_house = pd.DataFrame({
    "Area": [2000],
    "Bedrooms": [2],
    "Age": [20]
})

print("Predicted Price (₹ lakh):",
      model.predict(new_house)[0])

Predicted Price (₹ lakh): 79.37637830793908